DROP TABLE ENTRIES;
CREATE TABLE ENTRIES(
ID INTEGER PRIMARY KEY autoincrement,
YEAR INTEGER NOT NULL,
MONTH INTEGER NOT NULL,
DAY INTEGER NOT NULL,
ACCOUNT TEXT NOT NULL,
AMOUNT REAL NOT NULL,
CURRENCY TEXT NOT NULL,
DESCRIPTION TEXT NOT NULL
);

INSERT INTO ENTRIES (YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION) VALUES(2014,8,1,'PREMIER',18494.97,'GBP','Balance');
INSERT INTO ENTRIES (YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION) VALUES(2014,8,1,'ADVANCED',21932.36,'MYR','Balance');
INSERT INTO ENTRIES (YEAR,MONTH,DAY,ACCOUNT,AMOUNT,CURRENCY,DESCRIPTION) VALUES(2014,8,1,'SAVINGS',24983.12,'MYR','Balance');

CREATE TABLE USERS(
USERNAME TEXT,
SALT TEXT,
HASH TEXT
);
